services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo-data:/data/db
  web:
    build: .
    volumes:
      - .:/dynamic_pricing
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  sidekiq:
    depends_on:
      - redis
      - db
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/dynamic_pricing
    environment:
      - REDIS_URL=redis://redis:6379/1
volumes:
  mongo-data:
